### ISSUE TITLE
Can't run achd - assertion failed

### ISSUE THREAD

**Issue by Punkoivan** [achievecoin/AchieveCoin#1]
Hello team, I was trying to run achd -testnet but got this error:

```
achievecoin@node:~/src/AchieveCoin-0.1-beta/src$ ./achd -regtest
achd: crypto/common.h:138: int init_and_check_sodium(): Assertion `crypto_sign_verify_detached(sig, message, sizeof(message), pk) != 0' failed.
Aborted (core dumped)

```
It happens for prebuild binaries and for binaries that I compile. System is Ubuntu 16.04.02, x64, kernel is  4.4.0-64-generic.

What should I do to run achd and do some testing?

Thanks!

**Comment by argospam** [comment]
This error could mean you need a newer version of libsodium (at least 1.0.13).
 Try this:
```
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium-dev_1.0.13-1_amd64.deb
wget http://de.archive.ubuntu.com/ubuntu/pool/universe/libs/libsodium/libsodium18_1.0.13-1_amd64.deb
sudo dpkg -i libsodium*deb
```

**Comment by Punkoivan** [comment]
Yeah, it is OK now, thanks!
